# sigmoid-softmax 练习

In [1]:
import torch
import numpy as np

## 实现softmax函数

In [2]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用框架自带的softmax函数'''
    # 为避免exp(x)溢出,需要减去x中的最大值
    x_max = np.max(x)
    x -= x_max
    
    # 计算e的指数次幂
    exp_x = np.exp(x)
    sum_x = np.sum(exp_x, axis=-1, keepdims=True)
    
    # 计算softmax函数
    prob_x = torch.tensor(exp_x / sum_x)
    ##########
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - 
 torch.nn.functional.softmax(torch.tensor(test_data), dim=-1).numpy())**2 < 0.001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [3]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用框架自带的sigmoid函数'''
    prob_x = torch.tensor(1.0 / (1.0 + np.exp(-x)))
    ##########
    
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - 
torch.nn.functional.sigmoid(torch.tensor(test_data)).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [4]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数，不允许用框架自带的softmax_cross_entropy函数'''
    log_x = torch.log(x)
    qloss = -torch.sum(log_x * label, dim=1)
    loss = torch.mean(qloss)
    ##########
    return loss

test_data = np.random.normal(size=[10, 5])
prob = torch.nn.functional.softmax(torch.tensor(test_data), dim=1)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.
print(label)
torch_output = torch.nn.CrossEntropyLoss(reduction='none')(torch.tensor(test_data),
                                                           torch.tensor(label))
      
(torch.mean(torch_output 
 - softmax_ce(prob, label))**2 < 0.0001).numpy()

[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


array(True)

## 实现 sigmoid 交叉熵loss函数

In [5]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用框架自带的softmax_cross_entropy函数'''
    label = torch.tensor(label)
    log_x = torch.log(x)
    log_x2 = torch.log(1-x)
    loss = -torch.sum(label*log_x+(1-label)*log_x2)/len(x)
    ##########
    return loss

test_data = np.random.normal(size=[10])
prob = torch.nn.functional.sigmoid(torch.tensor(test_data))
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print(label)

torch_output = torch.nn.BCEWithLogitsLoss(reduction='none')(
    torch.tensor(test_data), torch.tensor(label))
(torch.mean(torch_output- 
 sigmoid_ce(prob, label))**2 < 0.0001).numpy()

[0. 1. 0. 1. 1. 0. 1. 0. 1. 0.]


array(True)