① 标量由只有一个元素的张量表示。导入pytorch库，建立两个标量x，y，初始化为3.0，2.0，输出两个标量的加法、乘法、除法、x的y次方。

In [1]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)
print(x + y)
print(x * y)
print(x / y)
print(x ** y)

tensor(5.)
tensor(6.)
tensor(1.5000)
tensor(9.)


## 2 向量

### 2.1 创建向量

① 可以将向量视为标量值组成的列表。创建一个[0,1,2,3]的向量z。并打印输出z

In [2]:
z = torch.arange(4)
z

tensor([0, 1, 2, 3])

### 2.2 访问向量元素

① 通过张量的索引来访问任一元素，输出z的第4个元素。

In [3]:
z[3]

tensor(3)

### 2.3 访问向量长度

① 输出张量（向量）z的长度/维度。

In [4]:
len(z)

4

### 2.4 向量求和

① 计算所有元素的和.输出向量z的所有元素的和

In [5]:
torch.sum(z)

tensor(6)

## 3 矩阵

### 3.1 创建矩阵

① 通过指定两个分量m和n来创建一个形状为m×n的矩阵。创建矩阵A=
        [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]

In [6]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

### 3.2 矩阵转置

① 输出矩阵A的转置。

In [7]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

### 3.3 对称矩阵

① 创建对称矩阵（symmetric matrix）B 等于其转置：$B = B^{T}$
B=
        [[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]]
查看矩阵B的转置，判断矩阵B的转置与B是否相等

In [8]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
print(B)
print(B.T)
print(B == B.T)

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### 3.4 多维矩阵（张量）

① 就像向量是标量的推广，矩阵是向量的推广一样，可以构建更多轴的数据结构。创建矩阵X=
       [[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]

In [9]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 3.5 矩阵相乘（对应元素相乘）

① 两个矩阵的按元素乘法称为哈达玛积（Hadamard product）（数学符号⊙）输出矩阵A⊙A

In [10]:
A * A

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

### 3.6 矩阵加标量 输出矩阵X+2

In [11]:
X += 2
X

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

### 3.7 矩阵求和
② 任意形状张量的元素和。输出张量A和X的元素和。

In [12]:
print(torch.sum(A))
print(torch.sum(X))

tensor(190)
tensor(324)


### 3.8 矩阵某轴求和（维度丢失）

①指定张量沿哪一个轴来通过求和降低维度。

In [13]:
print(torch.sum(A,0))
print(torch.sum(A,1))

tensor([40, 45, 50, 55])
tensor([ 6, 22, 38, 54, 70])


### 3.9 矩阵某轴求和（维度丢失）

① 指定张量沿哪一个轴来通过求和降低维度。输入张量Y=
       [[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]]
输出对第一个维度进行求和的结果。并输出其维度。
输出对第二个维度进行求和的结果。并输出其维度。
输出对第一、二两个维度进行求和的结果。并输出其维度。

In [14]:
Y = torch.arange(40).reshape(2,5,4)
y1 = torch.sum(Y,0)
print(y1)
print(y1.shape)

tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])
torch.Size([5, 4])


In [15]:
y2 = torch.sum(Y,1)
print(y2)
print(y2.shape)

tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]])
torch.Size([2, 4])


In [16]:
y3 = torch.sum(Y,[0,1])
print(y3)
print(y3.shape)

tensor([180, 190, 200, 210])
torch.Size([4])


### 3.10 矩阵平均值

① 一个与求和相关的量是平均值（mean或average）。输出矩阵A的平均值，输出矩阵A沿第一个维度的平均值

In [17]:
A = torch.arange(20,dtype = torch.float32).reshape(5,4)
print(A.mean())
print(A.mean(axis=0))

tensor(9.5000)
tensor([ 8.,  9., 10., 11.])


### 3.11 矩阵某轴求和（维度不丢失）

① 计算总和或均值时保持轴数不变。输出矩阵A沿第二个维度的和/平均值，维度不丢失。

In [18]:
sum_A = torch.sum(A,axis=1,keepdims=True)
mean_A = A.mean(axis=1)
print(sum_A)
print(mean_A)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000])


### 3.12 矩阵广播

① 通过广播将 A 除以 sum_A。

In [19]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

### 3.13 矩阵向量积

① A是一个m×n的矩阵，z是一个n×1的矩阵，矩阵向量积$Az$是一个长度为m的列向量，其第i个元素是点积$a^{⊤}_{i}z$。
输出Az

In [20]:
A = torch.arange(20,dtype = torch.float32).reshape(5,4)
x = torch.arange(4,dtype = torch.float32)
torch.mv(A,x)

tensor([ 14.,  38.,  62.,  86., 110.])

### 3.14 矩阵相乘（线性代数相乘）

① 可以将矩阵-矩阵乘法AB看作是简单地执行m次矩阵-向量积，并将结果拼接在一起，形成一个n×m矩阵。C是维度为[4,3]的全1矩阵，输出AC

In [21]:
C = torch.ones(4,3)
torch.mm(A,C)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

### 3.15 矩阵L2范数

① L2 范数是向量元素平方和的平方根：
$\|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n x_i^2}$  输出向量z的L2范数

In [22]:
z = torch.arange(4,dtype = torch.float32)
torch.norm(z)

tensor(3.7417)

### 3.16 矩阵F范数

① 矩阵的弗罗贝尼乌斯范数（Frobenius norm）是矩阵元素的平方和的平方根：$$\|\mathbf{X}\|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}$$
输出矩阵A的F范数

In [23]:
torch.norm(A)

tensor(49.6991)

# 4. 自动求导
① 假设想对函数$y=2\mathbf{z}^{\top}\mathbf{z}$关于列向量z求导。
将向量z的 requires_grad_ 打开

In [24]:
z.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

计算y,记得打开requires_grad

In [25]:
y = 2 * torch.dot(z,z)
y

tensor(28., grad_fn=<MulBackward0>)

设置y的反向传播

In [26]:
y.backward()

输出z的梯度

In [27]:
z.grad

tensor([ 0.,  4.,  8., 12.])